### ISSUE TITLE
marlin-fx for JDK 8

### ISSUE THREAD

**Issue by jimbok8** [bourgesl/marlin-fx#2]
I am still working with JDK 8 as I am using Netbeans and cannot get Netbeans to work with JDK 9+.
I am sure I had a copy of marlin-fx compatible with JDK 8 but managed to loose this when my PC crashed.
Do you have a copy marlin-fx that is compatible with JDK 8 (win64) that could be released please?
Thanks.

**Comment by bourgesl** [comment]
You should build your own marlinFX build for jdk8 as it patches the jfxrt.jar.
(For linux, such jar files are in the mapbench/lib repository too)

If you need Marlin (2d/swing), releases are available at:
https://github.com/bourgesl/marlin-renderer/releases

**Comment by jimbok8** [comment]
Thanks for the reply - yes I have now managed to build it.
For a newbie, the phrase "First time, import your local jfxrt.jar (from ${java.home}/lib/ext/jfxrt.jar) to your local maven repository" was confusing, as I was not sure exactly what to do.

Also, on the releases, the title mentions "JDK9+" which got me thinking that the repository was not valid for JDK8.
In addition, the linux binary (from Mapbench) failed I windows on "com/sun/ui/glass/win..." and I could not find the source code for these in the repository which got me thinking that it had changed radically for compatibility with JDK9.

Thanks for all your hard work in this area - this is much appreciated by JavaFX enthusiasts!
